spring.application.name=webecom

# ---------- DATABASE ----------
<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=2007
=======
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Hari@0410
>>>>>>> b2b2ad3ff8d17c11eb3550d673aec8644ec00c2a

# ---------- JPA / HIBERNATE ----------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ---------- ERRORS ----------
server.error.include-stacktrace=never
server.error.include-message=never
